name: lstmcpipe
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - python=3.7
  - astropy~=4.2
  - pip
  - pre-commit
  - ctapipe~=0.12
  - ruamel.yaml>=0.17
  - protobuf=3.20
  - pip:
      - ctaplot
      - ctapipe_io_lst
      - lstchain>=0.9.7
      - pyirf~=0.6.0
