name: lstMCpipe
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - python=3.7
  - astropy~=4.2
  - pip
  - ctapipe~=0.10.5
  - lstchain==0.7.3
  - pip:
#      - pytest_runner
#      - pytest-ordering
      - ctapipe_io_lst~=0.9.2
#      - ctaplot
      - pyirf~=0.4.0