# lstmcpipe generated config from PathConfigAllSkyFullDL1ab - 2024-10-25

workflow_kind: lstchain

# prod_id ex: local_no_n_islands. Default; v00 (if key left empty or None)
prod_id: 20240917_v0.10.12_src15_dec_min_2924_tuned

source_environment:
  source_file: /fefs/aswg/software/conda/etc/profile.d/conda.sh
  conda_env: lstchain-v0.10.7

slurm_config:
# dpps is the default account for lstanalyzer - other users should use aswg
  user_account: dpps
lstmcpipe_version: 0.11.3
prod_type: PathConfigAllSkyFullDL1ab
stages_to_run:
- dl1ab
- merge_dl1
- train_pipe
- dl1_to_dl2
- dl2_to_irfs
stages:
  dl1ab:
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_69.813_az_142.697_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_69.813_az_142.697_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_69.813_az_217.303_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_69.813_az_217.303_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_67.624_az_145.947_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_67.624_az_145.947_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_67.624_az_214.053_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_67.624_az_214.053_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_65.615_az_149.38_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_65.615_az_149.38_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_65.615_az_210.62_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_65.615_az_210.62_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_63.806_az_152.996_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_63.806_az_152.996_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_63.806_az_207.004_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_63.806_az_207.004_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_62.212_az_156.789_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_62.212_az_156.789_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_62.212_az_203.211_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_62.212_az_203.211_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_60.852_az_160.748_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_60.852_az_160.748_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_60.852_az_199.252_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_60.852_az_199.252_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_59.742_az_164.856_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_59.742_az_164.856_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_59.742_az_195.144_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_59.742_az_195.144_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_58.895_az_169.087_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_58.895_az_169.087_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_58.895_az_190.913_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_58.895_az_190.913_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_58.324_az_173.413_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_58.324_az_173.413_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_58.324_az_186.587_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_58.324_az_186.587_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_58.036_az_177.798_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/node_corsika_theta_58.036_az_177.798_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_69.813_az_142.697_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_69.813_az_142.697_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_69.813_az_217.303_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_69.813_az_217.303_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_67.624_az_145.947_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_67.624_az_145.947_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_67.624_az_214.053_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_67.624_az_214.053_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_65.615_az_149.38_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_65.615_az_149.38_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_65.615_az_210.62_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_65.615_az_210.62_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_63.806_az_152.996_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_63.806_az_152.996_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_63.806_az_207.004_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_63.806_az_207.004_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_62.212_az_156.789_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_62.212_az_156.789_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_62.212_az_203.211_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_62.212_az_203.211_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_60.852_az_160.748_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_60.852_az_160.748_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_60.852_az_199.252_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_60.852_az_199.252_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_59.742_az_164.856_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_59.742_az_164.856_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_59.742_az_195.144_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_59.742_az_195.144_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_58.895_az_169.087_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_58.895_az_169.087_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_58.895_az_190.913_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_58.895_az_190.913_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_58.324_az_173.413_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_58.324_az_173.413_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_58.324_az_186.587_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_58.324_az_186.587_
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240131_allsky_v0.10.5_all_dec_base/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_58.036_az_177.798_
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/node_corsika_theta_58.036_az_177.798_
  merge_dl1:
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/dl1_20240917_v0.10.12_src15_dec_min_2924_tuned_train_dec_min_2924_GammaDiffuse_merged.h5
    options: --pattern */*.h5 --no-image
    extra_slurm_options:
      partition: long
      time: 06:00:00
  - input: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924
    output: 
      /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/dl1_20240917_v0.10.12_src15_dec_min_2924_tuned_train_dec_min_2924_Protons_merged.h5
    options: --pattern */*.h5 --no-image
    extra_slurm_options:
      partition: long
      time: 06:00:00
  train_pipe:
  - input:
      gamma: 
        /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/GammaDiffuse/dec_min_2924/dl1_20240917_v0.10.12_src15_dec_min_2924_tuned_train_dec_min_2924_GammaDiffuse_merged.h5
      proton: 
        /fefs/aswg/data/mc/DL1/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/TrainingDataset/Protons/dec_min_2924/dl1_20240917_v0.10.12_src15_dec_min_2924_tuned_train_dec_min_2924_Protons_merged.h5
    output: 
      /fefs/aswg/data/models/AllSky/20240917_v0.10.12_src15_dec_min_2924_tuned/dec_min_2924
    extra_slurm_options:
      partition: xxl
      mem: 100G
      cpus-per-task: 16
      time: 03-00:00:00
  dl1_to_dl2: []
  dl2_to_irfs: []
