# lstmcpipe generated config from PathConfigAllSkyFullDL1ab - 2022-10-27

workflow_kind: lstchain

# prod_id ex: local_no_n_islands. Default; v00 (if key left empty or None)
prod_id: 20230508_v0.9.13_large_offset_crab_tuned

source_environment:
  source_file: /fefs/aswg/software/conda/etc/profile.d/conda.sh
  conda_env: lstchain-v0.9.13

slurm_config:
# dpps is the default account for lstanalyzer - other users should use aswg
  user_account: dpps

stages_to_run:
- dl1ab
- merge_dl1
stages:
  dl1ab:
  - input: /fefs/aswg/data/mc/DL0/LSTProd2/TestDataset/Crab_large_offset/sim_telarray/node_corsika_theta_52.374_az_240.004_
    output: /fefs/aswg/data/mc/DL1/AllSky/20230508_v0.9.13_large_offset_crab_tuned/TestingDataset/GammaDiffuse/node_theta_66.446_az_75.983_
  merge_dl1:
  - input: /fefs/aswg/data/mc/DL1/AllSky/20230508_v0.9.13_large_offset_crab_tuned/TestingDataset/GammaDiffuse/node_theta_66.446_az_75.983_
    output: /fefs/aswg/data/mc/DL1/AllSky/20230508_v0.9.13_large_offset_crab_tuned/TestingDataset/GammaDiffuse/dl1_20230508_v0.9.13_large_offset_crab_tuned_node_theta_66.446_az_75.983_merged.h5
    options: --pattern */*.h5 --no-image
    extra_slurm_options:
      partition: long
