workflow_kind: lstchain

prod_id: 20230517_v0.9.13_large_offset_crab_tuned

source_environment:
  source_file: /fefs/aswg/software/conda/etc/profile.d/conda.sh
  conda_env: lstchain-v0.9.13

slurm_config:
  user_account: dpps

stages_to_run:
- dl1ab
- merge_dl1
stages:
  dl1ab:
  - input: /fefs/aswg/data/mc/DL1/AllSky/20230517_v0.9.13_large_offset/TestingDataset/GammaDiffuse/node_theta_52.374_az_240.004_
    output: /fefs/aswg/data/mc/DL1/AllSky/20230517_v0.9.13_large_offset_crab_tuned/TestingDataset/GammaDiffuse/node_theta_52.374_az_240.004_
  merge_dl1:
  - input: /fefs/aswg/data/mc/DL1/AllSky/20230517_v0.9.13_large_offset_crab_tuned/TestingDataset/GammaDiffuse/node_theta_52.374_az_240.004_
    output: /fefs/aswg/data/mc/DL1/AllSky/20230517_v0.9.13_large_offset_crab_tuned/TestingDataset/GammaDiffuse/dl1_20230517_v0.9.13_large_offset_crab_tuned_node_theta_52.374_az_240.004_merged.h5
    options: --pattern */*.h5 --no-image
    extra_slurm_options:
      partition: long
