global_paths:
  workflow_kind:  lst
    # {lst, rta}
  prod_type:  prod5
    # {prod5, prod3}
  base_path_dl0: /fefs/aswg/data/mc
  # base_path_dl0: /fefs/aswg/workspace/enrique.garcia/workflow_r0_dl2_lst/
  obs_date: 20200629_prod5
    # {prod5: 20200629_prod5, pro3: 20190415 }
  zenith: zenith_20deg  # Only when prod5 (and therefore 20200629_prod5)
  pointing: south_pointing
  particles:
    - electron,
    - gamma,
    - gamma-diffuse,
    - proton
  offset_gammas:  # Only when prod5 (and therefore 20200629_prod5)
    - off0.0deg
    - off0.4deg

source_environment:
  - source: /fefs/aswg/software/virtual_env/.bashrc
  # - source: /fefs/home/enrique.garcia/.bashrc
  - env: cta
  # -env: lst-dev

stages_to_be_run:
  - R0_to_DL1
  - merge_and_copy_DL1
  - train_pipe
  - DL1_to_DL2
#  - DL2_to_DL3
