name: "Pull Request Docs Check"
on:
- push

defaults:
  run:
    shell: bash -l {0}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Install Conda env from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-env: true
          environment-file: environment.yml

      - name: Install doc dep
        run: |
          git config --global --add safe.directory '*'
          conda install make pandoc

      - name: Build docs
        run: |
          cd docs
          make html
          cd ..
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/_build/html/
      - name: Deploy to github pages
        # only run on push to master
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/_build/html
          CLEAN: true
          SINGLE_COMMIT: true
